# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQEventNetworkMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#SiemensIAQEventNetworkMessage.proto\x1a\x0cnanopb.proto\"2\n\x1dSiemensIAQEventNetworkMessage\x12\x11\n\tconnected\x18\x01 \x02(\x08')



_SIEMENSIAQEVENTNETWORKMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQEventNetworkMessage']
SiemensIAQEventNetworkMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQEventNetworkMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQEVENTNETWORKMESSAGE,
  '__module__' : 'SiemensIAQEventNetworkMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQEventNetworkMessage)
  })
_sym_db.RegisterMessage(SiemensIAQEventNetworkMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQEVENTNETWORKMESSAGE._serialized_start=53
  _SIEMENSIAQEVENTNETWORKMESSAGE._serialized_end=103
# @@protoc_insertion_point(module_scope)
