# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQEventOTAMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSiemensIAQEventOTAMessage.proto\x1a\x0cnanopb.proto\"M\n\x19SiemensIAQEventOTAMessage\x12\x17\n\x0f\x63urrent_version\x18\x01 \x02(\t\x12\x17\n\x0f\x64\x65sired_Version\x18\x02 \x02(\t')



_SIEMENSIAQEVENTOTAMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQEventOTAMessage']
SiemensIAQEventOTAMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQEventOTAMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQEVENTOTAMESSAGE,
  '__module__' : 'SiemensIAQEventOTAMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQEventOTAMessage)
  })
_sym_db.RegisterMessage(SiemensIAQEventOTAMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQEVENTOTAMESSAGE._serialized_start=49
  _SIEMENSIAQEVENTOTAMESSAGE._serialized_end=126
# @@protoc_insertion_point(module_scope)
