# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQEventOTAUpgradeMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&SiemensIAQEventOTAUpgradeMessage.proto\x1a\x0cnanopb.proto\"\xef\x04\n SiemensIAQEventOTAUpgradeMessage\x12T\n\x08progress\x18\x01 \x01(\x0b\x32@.SiemensIAQEventOTAUpgradeMessage.SiemensIAQEventOTAStateMessageH\x00\x12S\n\x06result\x18\x02 \x01(\x0b\x32\x41.SiemensIAQEventOTAUpgradeMessage.SiemensIAQEventOTAResultMessageH\x00\x1a\xe0\x02\n\x1eSiemensIAQEventOTAStateMessage\x12l\n\x11ota_http_progress\x18\x01 \x02(\x0e\x32Q.SiemensIAQEventOTAUpgradeMessage.SiemensIAQEventOTAStateMessage.OTAProgressState\x12\x16\n\x07percent\x18\x02 \x01(\rB\x05\x92?\x02\x38\x08\"\xb7\x01\n\x10OTAProgressState\x12\x10\n\x0cOTA_STARTING\x10\x00\x12\x12\n\x0eOTA_CONNECTING\x10\x01\x12\x10\n\x0cOTA_CHECKING\x10\x02\x12\x10\n\x0cOTA_ERASEING\x10\x03\x12\x13\n\x0fOTA_DOWNLOADING\x10\x04\x12\x11\n\rOTA_VERIFYING\x10\x05\x12\x0c\n\x08OTA_DONE\x10\x06\x12\x11\n\rOTA_REBOOTING\x10\x07\x12\x10\n\x0cOTA_ABORTING\x10\x08\x1a\x35\n\x1fSiemensIAQEventOTAResultMessage\x12\x12\n\nota_result\x18\x01 \x02(\tB\x06\n\x04ota_')



_SIEMENSIAQEVENTOTAUPGRADEMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQEventOTAUpgradeMessage']
_SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE = _SIEMENSIAQEVENTOTAUPGRADEMESSAGE.nested_types_by_name['SiemensIAQEventOTAStateMessage']
_SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTARESULTMESSAGE = _SIEMENSIAQEVENTOTAUPGRADEMESSAGE.nested_types_by_name['SiemensIAQEventOTAResultMessage']
_SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE_OTAPROGRESSSTATE = _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE.enum_types_by_name['OTAProgressState']
SiemensIAQEventOTAUpgradeMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQEventOTAUpgradeMessage', (_message.Message,), {

  'SiemensIAQEventOTAStateMessage' : _reflection.GeneratedProtocolMessageType('SiemensIAQEventOTAStateMessage', (_message.Message,), {
    'DESCRIPTOR' : _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE,
    '__module__' : 'SiemensIAQEventOTAUpgradeMessage_pb2'
    # @@protoc_insertion_point(class_scope:SiemensIAQEventOTAUpgradeMessage.SiemensIAQEventOTAStateMessage)
    })
  ,

  'SiemensIAQEventOTAResultMessage' : _reflection.GeneratedProtocolMessageType('SiemensIAQEventOTAResultMessage', (_message.Message,), {
    'DESCRIPTOR' : _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTARESULTMESSAGE,
    '__module__' : 'SiemensIAQEventOTAUpgradeMessage_pb2'
    # @@protoc_insertion_point(class_scope:SiemensIAQEventOTAUpgradeMessage.SiemensIAQEventOTAResultMessage)
    })
  ,
  'DESCRIPTOR' : _SIEMENSIAQEVENTOTAUPGRADEMESSAGE,
  '__module__' : 'SiemensIAQEventOTAUpgradeMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQEventOTAUpgradeMessage)
  })
_sym_db.RegisterMessage(SiemensIAQEventOTAUpgradeMessage)
_sym_db.RegisterMessage(SiemensIAQEventOTAUpgradeMessage.SiemensIAQEventOTAStateMessage)
_sym_db.RegisterMessage(SiemensIAQEventOTAUpgradeMessage.SiemensIAQEventOTAResultMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE.fields_by_name['percent']._options = None
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE.fields_by_name['percent']._serialized_options = b'\222?\0028\010'
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE._serialized_start=57
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE._serialized_end=680
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE._serialized_start=265
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE._serialized_end=617
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE_OTAPROGRESSSTATE._serialized_start=434
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTASTATEMESSAGE_OTAPROGRESSSTATE._serialized_end=617
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTARESULTMESSAGE._serialized_start=619
  _SIEMENSIAQEVENTOTAUPGRADEMESSAGE_SIEMENSIAQEVENTOTARESULTMESSAGE._serialized_end=672
# @@protoc_insertion_point(module_scope)
