# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQCommandLEDMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!SiemensIAQCommandLEDMessage.proto\x1a\x0cnanopb.proto\"\xae\x03\n\x1bSiemensIAQCommandLEDMessage\x12\x46\n\x04mode\x18\x01 \x02(\x0e\x32\x38.SiemensIAQCommandLEDMessage.SiemensIAQLEDBrightnessMode\x12\x19\n\nbrightness\x18\x02 \x02(\rB\x05\x92?\x02\x38\x08\x12\x46\n\x07lowbatt\x18\x03 \x01(\x0e\x32\x35.SiemensIAQCommandLEDMessage.SiemensIAQLowBatteryMode\"\x92\x01\n\x1bSiemensIAQLEDBrightnessMode\x12\x15\n\x11\x42RIGHTNESS_MANUAL\x10\x00\x12\x13\n\x0f\x42RIGHTNESS_AUTO\x10\x01\x12\x14\n\x10\x42RIGHTNESS_SLEEP\x10\x02\x12\x19\n\x15\x42RIGHTNESS_MATRIX_OFF\x10\x03\x12\x16\n\x12\x42RIGHTNESS_ALL_OFF\x10\x04\"O\n\x18SiemensIAQLowBatteryMode\x12\x18\n\x14LOWBATT_MODE_ENABLED\x10\x00\x12\x19\n\x15LOWBATT_MODE_DISABLED\x10\x01')



_SIEMENSIAQCOMMANDLEDMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQCommandLEDMessage']
_SIEMENSIAQCOMMANDLEDMESSAGE_SIEMENSIAQLEDBRIGHTNESSMODE = _SIEMENSIAQCOMMANDLEDMESSAGE.enum_types_by_name['SiemensIAQLEDBrightnessMode']
_SIEMENSIAQCOMMANDLEDMESSAGE_SIEMENSIAQLOWBATTERYMODE = _SIEMENSIAQCOMMANDLEDMESSAGE.enum_types_by_name['SiemensIAQLowBatteryMode']
SiemensIAQCommandLEDMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQCommandLEDMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQCOMMANDLEDMESSAGE,
  '__module__' : 'SiemensIAQCommandLEDMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQCommandLEDMessage)
  })
_sym_db.RegisterMessage(SiemensIAQCommandLEDMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQCOMMANDLEDMESSAGE.fields_by_name['brightness']._options = None
  _SIEMENSIAQCOMMANDLEDMESSAGE.fields_by_name['brightness']._serialized_options = b'\222?\0028\010'
  _SIEMENSIAQCOMMANDLEDMESSAGE._serialized_start=52
  _SIEMENSIAQCOMMANDLEDMESSAGE._serialized_end=482
  _SIEMENSIAQCOMMANDLEDMESSAGE_SIEMENSIAQLEDBRIGHTNESSMODE._serialized_start=255
  _SIEMENSIAQCOMMANDLEDMESSAGE_SIEMENSIAQLEDBRIGHTNESSMODE._serialized_end=401
  _SIEMENSIAQCOMMANDLEDMESSAGE_SIEMENSIAQLOWBATTERYMODE._serialized_start=403
  _SIEMENSIAQCOMMANDLEDMESSAGE_SIEMENSIAQLOWBATTERYMODE._serialized_end=482
# @@protoc_insertion_point(module_scope)
