# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQCommandSetTimezoneMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)SiemensIAQCommandSetTimezoneMessage.proto\x1a\x0cnanopb.proto\"K\n#SiemensIAQCommandSetTimezoneMessage\x12\x10\n\x08timezone\x18\x01 \x02(\t\x12\x12\n\nutc_offset\x18\x02 \x01(\x05')



_SIEMENSIAQCOMMANDSETTIMEZONEMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQCommandSetTimezoneMessage']
SiemensIAQCommandSetTimezoneMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQCommandSetTimezoneMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQCOMMANDSETTIMEZONEMESSAGE,
  '__module__' : 'SiemensIAQCommandSetTimezoneMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQCommandSetTimezoneMessage)
  })
_sym_db.RegisterMessage(SiemensIAQCommandSetTimezoneMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQCOMMANDSETTIMEZONEMESSAGE._serialized_start=59
  _SIEMENSIAQCOMMANDSETTIMEZONEMESSAGE._serialized_end=134
# @@protoc_insertion_point(module_scope)
