# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQCommandNotificationMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*SiemensIAQCommandNotificationMessage.proto\x1a\x0cnanopb.proto\"\xd0\x01\n$SiemensIAQCommandNotificationMessage\x12\x0f\n\x07message\x18\x01 \x02(\t\x12\x0f\n\x07\x64isplay\x18\x02 \x01(\t\x12\x18\n\tdirection\x18\x03 \x01(\x05\x42\x05\x92?\x02\x38\x08\x12\x14\n\x05speed\x18\x04 \x01(\rB\x05\x92?\x02\x38\x08\x12\x18\n\tbuzzer_hz\x18\x05 \x01(\rB\x05\x92?\x02\x38\x10\x12\x1e\n\x0f\x62uzzer_start_ms\x18\x06 \x01(\rB\x05\x92?\x02\x38\x10\x12\x1c\n\rbuzzer_end_ms\x18\x07 \x01(\rB\x05\x92?\x02\x38\x10')



_SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQCommandNotificationMessage']
SiemensIAQCommandNotificationMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQCommandNotificationMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE,
  '__module__' : 'SiemensIAQCommandNotificationMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQCommandNotificationMessage)
  })
_sym_db.RegisterMessage(SiemensIAQCommandNotificationMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['direction']._options = None
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['direction']._serialized_options = b'\222?\0028\010'
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['speed']._options = None
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['speed']._serialized_options = b'\222?\0028\010'
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['buzzer_hz']._options = None
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['buzzer_hz']._serialized_options = b'\222?\0028\020'
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['buzzer_start_ms']._options = None
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['buzzer_start_ms']._serialized_options = b'\222?\0028\020'
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['buzzer_end_ms']._options = None
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE.fields_by_name['buzzer_end_ms']._serialized_options = b'\222?\0028\020'
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE._serialized_start=61
  _SIEMENSIAQCOMMANDNOTIFICATIONMESSAGE._serialized_end=269
# @@protoc_insertion_point(module_scope)
