# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQEventPingPongMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$SiemensIAQEventPingPongMessage.proto\x1a\x0cnanopb.proto\"\xa2\x01\n\x1eSiemensIAQEventPingPongMessage\x12\x41\n\x04type\x18\x01 \x02(\x0e\x32\x33.SiemensIAQEventPingPongMessage.PingPongMessageType\x12\x12\n\nidentifier\x18\x02 \x02(\t\")\n\x13PingPongMessageType\x12\x08\n\x04PING\x10\x00\x12\x08\n\x04PONG\x10\x01')



_SIEMENSIAQEVENTPINGPONGMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQEventPingPongMessage']
_SIEMENSIAQEVENTPINGPONGMESSAGE_PINGPONGMESSAGETYPE = _SIEMENSIAQEVENTPINGPONGMESSAGE.enum_types_by_name['PingPongMessageType']
SiemensIAQEventPingPongMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQEventPingPongMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQEVENTPINGPONGMESSAGE,
  '__module__' : 'SiemensIAQEventPingPongMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQEventPingPongMessage)
  })
_sym_db.RegisterMessage(SiemensIAQEventPingPongMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQEVENTPINGPONGMESSAGE._serialized_start=55
  _SIEMENSIAQEVENTPINGPONGMESSAGE._serialized_end=217
  _SIEMENSIAQEVENTPINGPONGMESSAGE_PINGPONGMESSAGETYPE._serialized_start=176
  _SIEMENSIAQEVENTPINGPONGMESSAGE_PINGPONGMESSAGETYPE._serialized_end=217
# @@protoc_insertion_point(module_scope)
