# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQCommandOTAUpgradeMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(SiemensIAQCommandOTAUpgradeMessage.proto\x1a\x0cnanopb.proto\"L\n\"SiemensIAQCommandOTAUpgradeMessage\x12\x17\n\x0f\x64\x65sired_version\x18\x01 \x02(\t\x12\r\n\x05\x66orce\x18\x02 \x01(\x08')



_SIEMENSIAQCOMMANDOTAUPGRADEMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQCommandOTAUpgradeMessage']
SiemensIAQCommandOTAUpgradeMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQCommandOTAUpgradeMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQCOMMANDOTAUPGRADEMESSAGE,
  '__module__' : 'SiemensIAQCommandOTAUpgradeMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQCommandOTAUpgradeMessage)
  })
_sym_db.RegisterMessage(SiemensIAQCommandOTAUpgradeMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQCOMMANDOTAUPGRADEMESSAGE._serialized_start=58
  _SIEMENSIAQCOMMANDOTAUPGRADEMESSAGE._serialized_end=134
# @@protoc_insertion_point(module_scope)
