# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensLoRaIAQTimeSyncProtocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$SiemensLoRaIAQTimeSyncProtocol.proto\x1a\x0cnanopb.proto\"\x91\x03\n\x1eSiemensLoRaIAQTimeSyncProtocol\x12\x46\n\x07request\x18\x01 \x01(\x0b\x32\x33.SiemensLoRaIAQTimeSyncProtocol.LoRaTimeSyncRequestH\x00\x12H\n\x08response\x18\x02 \x01(\x0b\x32\x34.SiemensLoRaIAQTimeSyncProtocol.LoRaTimeSyncResponseH\x00\x1a&\n\x13LoRaTimeSyncRequest\x12\x0f\n\x07ignored\x18\x01 \x01(\t\x1a\xa3\x01\n\x14LoRaTimeSyncResponse\x12\x10\n\x08timezone\x18\x01 \x02(\t\x12\x16\n\x0eutc_in_seconds\x18\x02 \x02(\r\x12\x1d\n\x15utc_offset_in_seconds\x18\x03 \x02(\x05\x12\x0e\n\x06\x64st_on\x18\x04 \x01(\t\x12\x0f\n\x07\x64st_off\x18\x05 \x01(\t\x12!\n\x12\x64st_offset_minutes\x18\x06 \x01(\x05\x42\x05\x92?\x02\x38\x10:\x05\x92?\x02@\x01\x42\x08\n\x06\x61\x63tion')



_SIEMENSLORAIAQTIMESYNCPROTOCOL = DESCRIPTOR.message_types_by_name['SiemensLoRaIAQTimeSyncProtocol']
_SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCREQUEST = _SIEMENSLORAIAQTIMESYNCPROTOCOL.nested_types_by_name['LoRaTimeSyncRequest']
_SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCRESPONSE = _SIEMENSLORAIAQTIMESYNCPROTOCOL.nested_types_by_name['LoRaTimeSyncResponse']
SiemensLoRaIAQTimeSyncProtocol = _reflection.GeneratedProtocolMessageType('SiemensLoRaIAQTimeSyncProtocol', (_message.Message,), {

  'LoRaTimeSyncRequest' : _reflection.GeneratedProtocolMessageType('LoRaTimeSyncRequest', (_message.Message,), {
    'DESCRIPTOR' : _SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCREQUEST,
    '__module__' : 'SiemensLoRaIAQTimeSyncProtocol_pb2'
    # @@protoc_insertion_point(class_scope:SiemensLoRaIAQTimeSyncProtocol.LoRaTimeSyncRequest)
    })
  ,

  'LoRaTimeSyncResponse' : _reflection.GeneratedProtocolMessageType('LoRaTimeSyncResponse', (_message.Message,), {
    'DESCRIPTOR' : _SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCRESPONSE,
    '__module__' : 'SiemensLoRaIAQTimeSyncProtocol_pb2'
    # @@protoc_insertion_point(class_scope:SiemensLoRaIAQTimeSyncProtocol.LoRaTimeSyncResponse)
    })
  ,
  'DESCRIPTOR' : _SIEMENSLORAIAQTIMESYNCPROTOCOL,
  '__module__' : 'SiemensLoRaIAQTimeSyncProtocol_pb2'
  # @@protoc_insertion_point(class_scope:SiemensLoRaIAQTimeSyncProtocol)
  })
_sym_db.RegisterMessage(SiemensLoRaIAQTimeSyncProtocol)
_sym_db.RegisterMessage(SiemensLoRaIAQTimeSyncProtocol.LoRaTimeSyncRequest)
_sym_db.RegisterMessage(SiemensLoRaIAQTimeSyncProtocol.LoRaTimeSyncResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCRESPONSE.fields_by_name['dst_offset_minutes']._options = None
  _SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCRESPONSE.fields_by_name['dst_offset_minutes']._serialized_options = b'\222?\0028\020'
  _SIEMENSLORAIAQTIMESYNCPROTOCOL._options = None
  _SIEMENSLORAIAQTIMESYNCPROTOCOL._serialized_options = b'\222?\002@\001'
  _SIEMENSLORAIAQTIMESYNCPROTOCOL._serialized_start=55
  _SIEMENSLORAIAQTIMESYNCPROTOCOL._serialized_end=456
  _SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCREQUEST._serialized_start=235
  _SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCREQUEST._serialized_end=273
  _SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCRESPONSE._serialized_start=276
  _SIEMENSLORAIAQTIMESYNCPROTOCOL_LORATIMESYNCRESPONSE._serialized_end=439
# @@protoc_insertion_point(module_scope)
