# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQEventRSSIMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n SiemensIAQEventRSSIMessage.proto\x1a\x0cnanopb.proto\"\x98\x01\n\x1aSiemensIAQEventRSSIMessage\x12\x37\n\x06source\x18\x01 \x02(\x0e\x32\'.SiemensIAQEventRSSIMessage.RSSIContext\x12\x13\n\x04rssi\x18\x02 \x02(\x05\x42\x05\x92?\x02\x38\x10\",\n\x0bRSSIContext\x12\r\n\tDEVICE_RX\x10\x00\x12\x0e\n\nGATEWAY_RX\x10\x01')



_SIEMENSIAQEVENTRSSIMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQEventRSSIMessage']
_SIEMENSIAQEVENTRSSIMESSAGE_RSSICONTEXT = _SIEMENSIAQEVENTRSSIMESSAGE.enum_types_by_name['RSSIContext']
SiemensIAQEventRSSIMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQEventRSSIMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQEVENTRSSIMESSAGE,
  '__module__' : 'SiemensIAQEventRSSIMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQEventRSSIMessage)
  })
_sym_db.RegisterMessage(SiemensIAQEventRSSIMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQEVENTRSSIMESSAGE.fields_by_name['rssi']._options = None
  _SIEMENSIAQEVENTRSSIMESSAGE.fields_by_name['rssi']._serialized_options = b'\222?\0028\020'
  _SIEMENSIAQEVENTRSSIMESSAGE._serialized_start=51
  _SIEMENSIAQEVENTRSSIMESSAGE._serialized_end=203
  _SIEMENSIAQEVENTRSSIMESSAGE_RSSICONTEXT._serialized_start=159
  _SIEMENSIAQEVENTRSSIMESSAGE_RSSICONTEXT._serialized_end=203
# @@protoc_insertion_point(module_scope)
