# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQEventLEDMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSiemensIAQEventLEDMessage.proto\x1a\x0cnanopb.proto\"\x91\x02\n\x19SiemensIAQEventLEDMessage\x12\x44\n\x04mode\x18\x01 \x02(\x0e\x32\x36.SiemensIAQEventLEDMessage.SiemensIAQLEDBrightnessMode\x12\x19\n\nbrightness\x18\x02 \x02(\rB\x05\x92?\x02\x38\x08\"\x92\x01\n\x1bSiemensIAQLEDBrightnessMode\x12\x15\n\x11\x42RIGHTNESS_MANUAL\x10\x00\x12\x13\n\x0f\x42RIGHTNESS_AUTO\x10\x01\x12\x14\n\x10\x42RIGHTNESS_SLEEP\x10\x02\x12\x19\n\x15\x42RIGHTNESS_MATRIX_OFF\x10\x03\x12\x16\n\x12\x42RIGHTNESS_ALL_OFF\x10\x04')



_SIEMENSIAQEVENTLEDMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQEventLEDMessage']
_SIEMENSIAQEVENTLEDMESSAGE_SIEMENSIAQLEDBRIGHTNESSMODE = _SIEMENSIAQEVENTLEDMESSAGE.enum_types_by_name['SiemensIAQLEDBrightnessMode']
SiemensIAQEventLEDMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQEventLEDMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQEVENTLEDMESSAGE,
  '__module__' : 'SiemensIAQEventLEDMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQEventLEDMessage)
  })
_sym_db.RegisterMessage(SiemensIAQEventLEDMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQEVENTLEDMESSAGE.fields_by_name['brightness']._options = None
  _SIEMENSIAQEVENTLEDMESSAGE.fields_by_name['brightness']._serialized_options = b'\222?\0028\010'
  _SIEMENSIAQEVENTLEDMESSAGE._serialized_start=50
  _SIEMENSIAQEVENTLEDMESSAGE._serialized_end=323
  _SIEMENSIAQEVENTLEDMESSAGE_SIEMENSIAQLEDBRIGHTNESSMODE._serialized_start=177
  _SIEMENSIAQEVENTLEDMESSAGE_SIEMENSIAQLEDBRIGHTNESSMODE._serialized_end=323
# @@protoc_insertion_point(module_scope)
