# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQCommandSysctrlMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%SiemensIAQCommandSysctrlMessage.proto\x1a\x0cnanopb.proto\"\x88\x02\n\x1fSiemensIAQCommandSysctrlMessage\x12G\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x36.SiemensIAQCommandSysctrlMessage.SiemensSysctrlCommand\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\"\x8d\x01\n\x15SiemensSysctrlCommand\x12\x12\n\x0eSYSCTRL_REBOOT\x10\x00\x12\x19\n\x15SYSCTRL_VOC_CAL_RESET\x10\x01\x12\x19\n\x15SYSCTRL_FACTORY_RESET\x10\x02\x12\x15\n\x11SYSCTRL_TIME_SYNC\x10\x03\x12\x13\n\x0fSYSCTRL_UNKNOWN\x10\x04')



_SIEMENSIAQCOMMANDSYSCTRLMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQCommandSysctrlMessage']
_SIEMENSIAQCOMMANDSYSCTRLMESSAGE_SIEMENSSYSCTRLCOMMAND = _SIEMENSIAQCOMMANDSYSCTRLMESSAGE.enum_types_by_name['SiemensSysctrlCommand']
SiemensIAQCommandSysctrlMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQCommandSysctrlMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQCOMMANDSYSCTRLMESSAGE,
  '__module__' : 'SiemensIAQCommandSysctrlMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQCommandSysctrlMessage)
  })
_sym_db.RegisterMessage(SiemensIAQCommandSysctrlMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQCOMMANDSYSCTRLMESSAGE._serialized_start=56
  _SIEMENSIAQCOMMANDSYSCTRLMESSAGE._serialized_end=320
  _SIEMENSIAQCOMMANDSYSCTRLMESSAGE_SIEMENSSYSCTRLCOMMAND._serialized_start=179
  _SIEMENSIAQCOMMANDSYSCTRLMESSAGE_SIEMENSSYSCTRLCOMMAND._serialized_end=320
# @@protoc_insertion_point(module_scope)
