# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SiemensIAQEventBatteryMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#SiemensIAQEventBatteryMessage.proto\x1a\x0cnanopb.proto\"a\n\x1dSiemensIAQEventBatteryMessage\x12\x1d\n\x0e\x63harge_percent\x18\x01 \x02(\rB\x05\x92?\x02\x38\x08\x12\x0f\n\x07plugged\x18\x02 \x02(\x08\x12\x10\n\x08\x63harging\x18\x03 \x02(\x08')



_SIEMENSIAQEVENTBATTERYMESSAGE = DESCRIPTOR.message_types_by_name['SiemensIAQEventBatteryMessage']
SiemensIAQEventBatteryMessage = _reflection.GeneratedProtocolMessageType('SiemensIAQEventBatteryMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIEMENSIAQEVENTBATTERYMESSAGE,
  '__module__' : 'SiemensIAQEventBatteryMessage_pb2'
  # @@protoc_insertion_point(class_scope:SiemensIAQEventBatteryMessage)
  })
_sym_db.RegisterMessage(SiemensIAQEventBatteryMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIEMENSIAQEVENTBATTERYMESSAGE.fields_by_name['charge_percent']._options = None
  _SIEMENSIAQEVENTBATTERYMESSAGE.fields_by_name['charge_percent']._serialized_options = b'\222?\0028\010'
  _SIEMENSIAQEVENTBATTERYMESSAGE._serialized_start=53
  _SIEMENSIAQEVENTBATTERYMESSAGE._serialized_end=150
# @@protoc_insertion_point(module_scope)
